import assert from "node:assert/strict";
import test,{after} from "node:test";
import type {EmbeddingProvider} from "../apps/server/src/fabric/embeddings.js";
import {createFabric} from "../apps/server/src/fabric/index.js";
import {cleanupDatabases,databaseFixture} from "./database.js";
after(cleanupDatabases);

class FixtureEmbeddings implements EmbeddingProvider{
 readonly model="fixture-semantic-v1";inputs:string[]=[];
 async embed(texts:string[]){this.inputs.push(...texts);return texts.map((raw)=>{const text=raw.toLowerCase();if(text.includes("comparison reference"))return[-1,0,0,0];if(text.trim()==="vehicle repair"||text.includes("automobile maintenance"))return[1,0,0,0];if(text.includes("workplace collaboration")||text.includes("team coordination"))return[0,1,0,0];if(text.includes("cat wellness")||text.includes("feline health"))return[0,0,1,0];if(text.includes("sea route")||text.includes("ocean navigation"))return[0,0,0,1];if(text.includes("weak vehicle mention"))return[0.4,Math.sqrt(0.84),0,0];return[-1,0,0,0];});}
}
class FailingEmbeddings implements EmbeddingProvider{readonly model="unavailable";async embed(_texts:string[]):Promise<number[][]>{throw new Error("fixture provider unavailable");}}

test("semantic and hybrid retrieval are derived, deterministic, filtered, and lifecycle-consistent",async()=>{
 const fixture=await databaseFixture();const provider=new FixtureEmbeddings();const fabric=createFabric(fixture.databaseUrl,provider);const {catalog}=fixture;
 try{
  const first=await catalog.createProject({name:"Library"});const second=await catalog.createProject({name:"Workshop"});const fields=[{name:"title",type:"string" as const,required:true},{name:"notes",type:"string" as const},{name:"opaque",type:"string" as const},{name:"url",type:"string" as const}];const a=await catalog.createStore({projectId:first.id,name:"Guides",fields});const b=await catalog.createStore({projectId:second.id,name:"References",fields});
  const conceptual=await catalog.createRecord({projectId:first.id,storeId:a.id,data:{title:"Automobile maintenance handbook",notes:"Engine servicing procedures",opaque:"abc1234567890machine987654321",url:"https://example.test/vehicle-repair"}});const lexicalDecoy=await catalog.createRecord({projectId:second.id,storeId:b.id,data:{title:"Vehicle repair comparison reference",notes:"A comparison term, not the underlying subject"}});const collaboration=await catalog.createRecord({projectId:first.id,storeId:a.id,data:{title:"Team coordination practices",notes:"Shared planning and communication"}});
  const semantic=await fabric.search.search({query:"workplace collaboration",mode:"semantic"});assert.equal(semantic.results[0]?.record.id,collaboration.id);assert.equal(semantic.results[0]?.ranking.semanticFound,true);assert.equal(semantic.results[0]?.ranking.lexicalFound,false);
  const lexical=await fabric.search.search({query:"vehicle repair",mode:"lexical"});assert.equal(lexical.results[0]?.record.id,lexicalDecoy.id);const hybrid=await fabric.search.search({query:"vehicle repair",mode:"hybrid"});assert.equal(hybrid.results[0]?.record.id,conceptual.id);assert.equal(hybrid.results[0]?.ranking.semanticFound,true);assert.ok(hybrid.results[0]!.ranking.hybridScore>hybrid.results[1]!.ranking.hybridScore);
  assert.ok(provider.inputs.every((text)=>!text.includes("abc1234567890machine987654321")&&!text.includes("https://example.test")));
  const filtered=await fabric.search.search({query:"vehicle repair",mode:"hybrid",projectIds:[second.id]});assert.ok(filtered.results.every((result)=>result.project.id===second.id));const again=await fabric.search.search({query:"vehicle repair",mode:"hybrid"});assert.deepEqual(hybrid.results.map((x)=>x.record.id),again.results.map((x)=>x.record.id));
  const created=await catalog.createRecord({projectId:first.id,storeId:a.id,data:{title:"Feline health notes"}});assert.equal((await fabric.search.search({query:"cat wellness",mode:"semantic"})).results[0]?.record.id,created.id);await catalog.updateRecord({projectId:first.id,storeId:a.id,recordId:created.id,data:{title:"Ocean navigation notes"},replace:true});assert.ok((await fabric.search.search({query:"cat wellness",mode:"semantic"})).results.every((x)=>x.record.id!==created.id));assert.equal((await fabric.search.search({query:"sea route",mode:"semantic"})).results[0]?.record.id,created.id);await catalog.archiveRecord(first.id,a.id,created.id);assert.ok((await fabric.search.search({query:"sea route",mode:"semantic"})).results.every((x)=>x.record.id!==created.id));
  const before=(await fabric.search.search({query:"vehicle repair",mode:"semantic"})).results.map((x)=>x.record.id);await fabric.search.rebuildSemanticIndex();assert.equal(Number((await fabric.repository.pool.query("SELECT count(*) AS count FROM fabric_semantic_documents")).rows[0].count),0);const rebuilt=(await fabric.search.search({query:"vehicle repair",mode:"semantic"})).results.map((x)=>x.record.id);assert.deepEqual(rebuilt,before);
  const weak=await catalog.createRecord({projectId:first.id,storeId:a.id,data:{title:"Weak vehicle mention"}});const context=await fabric.context.request({query:"vehicle repair unrelated absent",maxRecords:10});assert.ok(context.selections.length<10);assert.ok(context.selections.every((x)=>x.record.id!==weak.id));
 }finally{await fabric.repository.close();}
});

test("provider failure falls back lexically while Core remains correct",async()=>{const fixture=await databaseFixture();const fabric=createFabric(fixture.databaseUrl,new FailingEmbeddings());try{const project=await fixture.catalog.createProject({name:"Independent Core"});const store=await fixture.catalog.createStore({projectId:project.id,name:"Data",fields:[{name:"title",type:"string",required:true}]});const record=await fixture.catalog.createRecord({projectId:project.id,storeId:store.id,data:{title:"Exact lexical evidence"}});const hybrid=await fabric.search.search({query:"Exact lexical evidence"});assert.equal(hybrid.results[0]?.record.id,record.id);assert.equal(hybrid.diagnostics.semanticStatus,"unavailable");assert.match(hybrid.diagnostics.semanticError??"",/fixture provider unavailable/);const semantic=await fabric.search.search({query:"anything",mode:"semantic"});assert.equal(semantic.results.length,0);assert.equal(semantic.diagnostics.semanticStatus,"unavailable");assert.equal((await fixture.catalog.getRecord(project.id,store.id,record.id)).id,record.id);}finally{await fabric.repository.close();}});
