import assert from "node:assert/strict";
import test,{after} from "node:test";
import {createFabric} from "../src/fabric/index.js";
import type {StoreAuthorityPolicy} from "../src/fabric/repository.js";
import {cleanupDatabases,databaseFixture} from "./database.js";
after(cleanupDatabases);
const fields=[{name:"subject",type:"string" as const,required:true},{name:"value",type:"string" as const,required:true},{name:"status",type:"string" as const},{name:"effectiveAt",type:"date" as const},{name:"detail",type:"string" as const}];
const policy=(storeId:string,authorityRole:StoreAuthorityPolicy["authorityRole"],canonicalStoreId?:string):StoreAuthorityPolicy=>({storeId,authorityRole,...(canonicalStoreId&&{canonicalStoreId}),equivalenceKind:"same_fact",identityFields:["subject"],comparisonFields:["value"],effectiveTimeFields:["effectiveAt"],currentField:"status",currentValues:["current"],historicalValues:["historical"]});

test("authority policy prefers canonical/current facts and exposes resolved conflicts",async()=>{const fixture=await databaseFixture();const fabric=createFabric(fixture.databaseUrl,null);try{const project=await fixture.catalog.createProject({name:"Policy"});const canonicalStore=await fixture.catalog.createStore({projectId:project.id,name:"Canonical",fields});const mirrorStore=await fixture.catalog.createStore({projectId:project.id,name:"Mirror",fields});await fabric.repository.setStoreAuthorityPolicy(policy(canonicalStore.id,"canonical"));await fabric.repository.setStoreAuthorityPolicy(policy(mirrorStore.id,"mirror",canonicalStore.id));const canonical=await fixture.catalog.createRecord({projectId:project.id,storeId:canonicalStore.id,data:{subject:"account state",value:"active",status:"current",effectiveAt:"2026-01-01"}});const mirror=await fixture.catalog.createRecord({projectId:project.id,storeId:mirrorStore.id,data:{subject:"account state",value:"pending",status:"current",effectiveAt:"2026-02-01",detail:"richer mirror description"}});const searchBefore=(await fabric.search.search({query:"account state",mode:"lexical"})).results.map((x)=>x.record.id);const context=await fabric.context.request({query:"account state active pending",maxRecords:5});assert.ok(context.selections.some((x)=>x.record.id===canonical.id));assert.ok(context.selections.every((x)=>x.record.id!==mirror.id));const decision=context.diagnostics.authorityDecisions[0]!;assert.equal(decision.preferredRecordId,canonical.id);assert.deepEqual(decision.suppressedRecordIds,[mirror.id]);assert.equal(decision.contradictionStatus,"resolved");assert.ok(decision.records.find((x)=>x.recordId===canonical.id)?.conflictsWith.includes(mirror.id));const searchAfter=(await fabric.search.search({query:"account state",mode:"lexical"})).results.map((x)=>x.record.id);assert.deepEqual(searchAfter,searchBefore);}finally{await fabric.repository.close();}});

test("currentness beats historical write recency and effective time resolves comparable current facts",async()=>{const fixture=await databaseFixture();const fabric=createFabric(fixture.databaseUrl,null);try{const project=await fixture.catalog.createProject({name:"Time"});const currentStore=await fixture.catalog.createStore({projectId:project.id,name:"Current",fields});const historyStore=await fixture.catalog.createStore({projectId:project.id,name:"History",fields});await fabric.repository.setStoreAuthorityPolicy(policy(currentStore.id,"primary"));await fabric.repository.setStoreAuthorityPolicy(policy(historyStore.id,"primary",currentStore.id));const current=await fixture.catalog.createRecord({projectId:project.id,storeId:currentStore.id,data:{subject:"membership state",value:"enabled",status:"current",effectiveAt:"2025-01-01"}});const historical=await fixture.catalog.createRecord({projectId:project.id,storeId:historyStore.id,data:{subject:"membership state",value:"disabled",status:"historical",effectiveAt:"2026-09-01",detail:"recently written history"}});let context=await fabric.context.request({query:"membership state enabled disabled",maxRecords:5});assert.equal(context.diagnostics.authorityDecisions[0]?.preferredRecordId,current.id);assert.ok(context.selections.every((x)=>x.record.id!==historical.id));const newer=await fixture.catalog.createRecord({projectId:project.id,storeId:historyStore.id,data:{subject:"membership state",value:"enabled new",status:"current",effectiveAt:"2026-08-01"}});context=await fabric.context.request({query:"membership state enabled new",maxRecords:5});assert.equal(context.diagnostics.authorityDecisions[0]?.preferredRecordId,newer.id);}finally{await fabric.repository.close();}});

test("equal-authority contradiction remains visible and related records are not equated without policy",async()=>{const fixture=await databaseFixture();const fabric=createFabric(fixture.databaseUrl,null);try{const project=await fixture.catalog.createProject({name:"Ambiguity"});const leftStore=await fixture.catalog.createStore({projectId:project.id,name:"Left",fields});const rightStore=await fixture.catalog.createStore({projectId:project.id,name:"Right",fields});await fabric.repository.setStoreAuthorityPolicy(policy(leftStore.id,"primary"));await fabric.repository.setStoreAuthorityPolicy(policy(rightStore.id,"primary",leftStore.id));const left=await fixture.catalog.createRecord({projectId:project.id,storeId:leftStore.id,data:{subject:"current employer",value:"Company Alpha",status:"current"}});const right=await fixture.catalog.createRecord({projectId:project.id,storeId:rightStore.id,data:{subject:"current employer",value:"Company Beta",status:"current"}});const timelineStore=await fixture.catalog.createStore({projectId:project.id,name:"Timeline",fields});const event=await fixture.catalog.createRecord({projectId:project.id,storeId:timelineStore.id,data:{subject:"employment event",value:"Company Alpha role began",status:"historical"}});const context=await fabric.context.request({query:"current employer Company Alpha Company Beta employment event",maxRecords:10});assert.ok(context.selections.some((x)=>x.record.id===left.id));assert.ok(context.selections.some((x)=>x.record.id===right.id));assert.ok(context.selections.some((x)=>x.record.id===event.id));const decision=context.diagnostics.authorityDecisions[0]!;assert.equal(decision.contradictionStatus,"unresolved");assert.equal(decision.unresolvedAmbiguity,true);assert.equal(decision.preferredRecordId,undefined);assert.equal(context.diagnostics.unresolvedConflicts,1);}finally{await fabric.repository.close();}});

test("authority subsystem failure cannot block Core and context fails open with diagnostics",async()=>{const fixture=await databaseFixture();const fabric=createFabric(fixture.databaseUrl,null);try{await fabric.repository.pool.query("DROP TABLE fabric_record_authority_policies");await fabric.repository.pool.query("DROP TABLE fabric_store_authority_policies");const project=await fixture.catalog.createProject({name:"Core survives"});const store=await fixture.catalog.createStore({projectId:project.id,name:"Records",fields});const record=await fixture.catalog.createRecord({projectId:project.id,storeId:store.id,data:{subject:"independent fact",value:"available"}});assert.equal((await fixture.catalog.getRecord(project.id,store.id,record.id)).id,record.id);const context=await fabric.context.request({query:"independent fact available",maxRecords:3});assert.equal(context.diagnostics.authorityStatus,"unavailable");assert.match(context.diagnostics.authorityError??"",/fabric_store_authority_policies/);assert.ok(context.selections.some((x)=>x.record.id===record.id));}finally{await fabric.repository.close();}});
