import {createHash} from "node:crypto";
import type {FabricSearchRepository,RecordAuthorityPolicy,StoreAuthorityPolicy} from "./repository.js";
import type {AuthorityDecision,AuthorityRole,FabricResult} from "./types.js";

const ROLE_ORDER:Record<AuthorityRole,number>={canonical:6,primary:5,unknown:4,supporting:3,mirror:2,derived:2,historical:1};
const normalize=(value:unknown):unknown=>typeof value==="string"?value.trim().toLocaleLowerCase():Array.isArray(value)?value.map(normalize):value&&typeof value==="object"?Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,normalize(item)])):value;
const field=(data:Record<string,unknown>,path:string)=>path.split(".").reduce<unknown>((value,key)=>value&&typeof value==="object"&&!Array.isArray(value)?(value as Record<string,unknown>)[key]:undefined,data);
const iso=(value:unknown)=>{if(typeof value!=="string")return undefined;const timestamp=Date.parse(value);return Number.isNaN(timestamp)?undefined:new Date(timestamp).toISOString();};
type Candidate={result:FabricResult;store:StoreAuthorityPolicy;record?:RecordAuthorityPolicy;role:AuthorityRole;currentness:"current"|"historical"|"unknown";effectiveAt?:string;identity:unknown[];groupId:string};

export class FabricAuthorityService{
 constructor(readonly repository:FabricSearchRepository){}
 async apply(results:FabricResult[]):Promise<{results:FabricResult[];decisions:AuthorityDecision[]}>{
  const policies=await this.repository.authorityPolicies([...new Set(results.map((x)=>x.store.id))],results.map((x)=>x.record.id));const stores=new Map(policies.stores.map((x)=>[x.storeId,x]));const records=new Map(policies.records.map((x)=>[x.recordId,x]));const groups=new Map<string,Candidate[]>();
  for(const result of results){const store=stores.get(result.store.id);if(!store)continue;const identity=store.identityFields.map((path)=>normalize(field(result.record.data,path)));if(identity.some((value)=>value===undefined||value===null||value===""))continue;const family=store.canonicalStoreId??store.storeId;const raw=`${family}|${store.equivalenceKind}|${JSON.stringify(identity)}`;const groupId=createHash("sha256").update(raw).digest("hex").slice(0,24);const record=records.get(result.record.id);const role=record?.authorityRole??store.authorityRole;const marker=store.currentField?String(field(result.record.data,store.currentField)??"").toLocaleLowerCase():"";const currentness:Candidate["currentness"]=store.currentValues.map((x)=>x.toLocaleLowerCase()).includes(marker)?"current":store.historicalValues.map((x)=>x.toLocaleLowerCase()).includes(marker)?"historical":"unknown";const effectiveAt=record?.effectiveAt??store.effectiveTimeFields.map((path)=>iso(field(result.record.data,path))).find(Boolean);const candidate:Candidate={result,store,record,role,currentness,effectiveAt,identity,groupId};groups.set(groupId,[...(groups.get(groupId)??[]),candidate]);}
  const retained=new Set(results.map((x)=>x.record.id));const decisions:AuthorityDecision[]=[];
  for(const [groupId,candidates] of groups){if(candidates.length<2)continue;const kind=candidates[0]!.store.equivalenceKind;const conflictMap=new Map(candidates.map((x)=>[x.result.record.id,[] as string[]]));if(kind==="same_fact")for(let i=0;i<candidates.length;i++)for(let j=i+1;j<candidates.length;j++){const a=candidates[i]!,b=candidates[j]!;const length=Math.min(a.store.comparisonFields.length,b.store.comparisonFields.length);let conflict=false;for(let n=0;n<length;n++){const av=field(a.result.record.data,a.store.comparisonFields[n]!),bv=field(b.result.record.data,b.store.comparisonFields[n]!);if(av!==undefined&&bv!==undefined&&JSON.stringify(normalize(av))!==JSON.stringify(normalize(bv))){conflict=true;break;}}if(conflict){conflictMap.get(a.result.record.id)!.push(b.result.record.id);conflictMap.get(b.result.record.id)!.push(a.result.record.id);}}
   const superseder=candidates.find((candidate)=>candidates.some((other)=>candidate.record?.supersedesRecordId===other.result.record.id));const currentOrder=(value:Candidate["currentness"])=>value==="current"?2:value==="unknown"?1:0;const ordered=[...candidates].sort((a,b)=>(superseder?.result.record.id===b.result.record.id?1:0)-(superseder?.result.record.id===a.result.record.id?1:0)||ROLE_ORDER[b.role]-ROLE_ORDER[a.role]||currentOrder(b.currentness)-currentOrder(a.currentness)||(Date.parse(b.effectiveAt??"")||0)-(Date.parse(a.effectiveAt??"")||0)||a.result.record.id.localeCompare(b.result.record.id));const preferred=ordered[0]!;const second=ordered[1]!;const rankKey=(candidate:Candidate)=>[superseder?.result.record.id===candidate.result.record.id?1:0,ROLE_ORDER[candidate.role],currentOrder(candidate.currentness),Date.parse(candidate.effectiveAt??"")||0].join("|");const unique=rankKey(preferred)!==rankKey(second);const hasConflict=[...conflictMap.values()].some((items)=>items.length);const unresolved=hasConflict&&!unique;const suppressed:string[]=[];
   if(unique)for(const candidate of candidates){if(candidate===preferred)continue;const suppress=kind==="same_fact"||["mirror","derived","historical"].includes(candidate.role);if(suppress){retained.delete(candidate.result.record.id);suppressed.push(candidate.result.record.id);}}
   const reason=unresolved?"Equivalent records make conflicting claims with equal authority/currentness; all alternatives preserved.":unique?`Preferred ${preferred.role} record using explicit authority, currentness, supersession, then effective-time precedence; updatedAt was not used.`:"Equivalent records have no deterministic authority distinction; existing diversification may apply.";decisions.push({equivalenceGroupId:groupId,equivalenceKind:kind,identity:preferred.identity,records:candidates.map((candidate)=>({recordId:candidate.result.record.id,authorityRole:candidate.role,relation:candidate.role,currentness:candidate.currentness,effectiveAt:candidate.effectiveAt??null,conflictsWith:conflictMap.get(candidate.result.record.id)!})),...(unique&&{preferredRecordId:preferred.result.record.id}),suppressedRecordIds:suppressed,reason,contradictionStatus:hasConflict?(unresolved?"unresolved":"resolved"):"none",unresolvedAmbiguity:unresolved});
  }
  return {results:results.filter((result)=>retained.has(result.record.id)),decisions};
 }
}
