import { Pool } from "pg";
import type { AtlasRecord } from "../types.js";
import type {AuthorityRole} from "./types.js";
export type SearchRow={project_id:string;project_name:string;store_id:string;store_name:string;record:AtlasRecord;text_rank:number;term_coverage:number;exact_phrase:boolean;candidate_count:number;matched_term_count?:number;lexical_score?:number};
export type SemanticRow={project_id:string;project_name:string;store_id:string;store_name:string;record:AtlasRecord;semantic_similarity:number;candidate_count:number};
export type SemanticIndexWork={recordId:string;text:string;sourceUpdatedAt:string};
import type { RetrievalDocument as ExternalFabricDocument } from "../retrieval/indexing.js";
export type { RetrievalDocument as ExternalFabricDocument } from "../retrieval/indexing.js";
export type StoreAuthorityPolicy={storeId:string;authorityRole:AuthorityRole;canonicalStoreId?:string;equivalenceKind:"same_entity"|"same_fact";identityFields:string[];comparisonFields:string[];effectiveTimeFields:string[];currentField?:string;currentValues:string[];historicalValues:string[];note?:string};
export type RecordAuthorityPolicy={recordId:string;authorityRole?:AuthorityRole;effectiveAt?:string;supersedesRecordId?:string;note?:string};
export class FabricSearchRepository{
    readonly pool:Pool; constructor(databaseUrl:string){this.pool=new Pool({connectionString:databaseUrl});} async close(){await this.pool.end();}
    async synchronize(){const client=await this.pool.connect(); try{await client.query("BEGIN"); await client.query("SELECT pg_advisory_xact_lock($1)",[0x46414252]); await client.query(`
      INSERT INTO fabric_search_documents(record_id,project_id,store_id,project_name,store_name,field_text,searchable_text,display_text,source_updated_at,indexed_at,source_type,source_id,record_data,record_created_at,record_updated_at)
      SELECT r.id,p.id,s.id,p.name,s.name,fabric_searchable_jsonb(r.data),concat_ws(' ',p.name,s.name,fabric_searchable_jsonb(r.data)),fabric_flatten_jsonb(r.data),greatest(r.updated_at,s.updated_at,p.updated_at),now(),CASE WHEN p.id='d99a6c45-a4ec-5ef6-8f22-c07d31f8bb38'::uuid THEN 'portfolio-draft' ELSE 'atlas-core' END,r.id::text,r.data,r.created_at,r.updated_at
      FROM records r JOIN stores s ON s.id=r.store_id JOIN projects p ON p.id=s.project_id
      WHERE r.archived_at IS NULL AND s.archived_at IS NULL AND p.archived_at IS NULL
      ON CONFLICT(record_id) DO UPDATE SET project_id=excluded.project_id,store_id=excluded.store_id,project_name=excluded.project_name,store_name=excluded.store_name,field_text=excluded.field_text,searchable_text=excluded.searchable_text,display_text=excluded.display_text,source_updated_at=excluded.source_updated_at,indexed_at=now(),source_type=excluded.source_type,source_id=excluded.source_id,record_data=excluded.record_data,record_created_at=excluded.record_created_at,record_updated_at=excluded.record_updated_at
      WHERE fabric_search_documents.source_updated_at IS DISTINCT FROM excluded.source_updated_at OR fabric_search_documents.searchable_text IS DISTINCT FROM excluded.searchable_text OR fabric_search_documents.display_text IS DISTINCT FROM excluded.display_text OR fabric_search_documents.record_data IS DISTINCT FROM excluded.record_data`);
      await client.query(`DELETE FROM fabric_search_documents d WHERE d.source_type IN ('atlas-core','portfolio-draft') AND NOT EXISTS(SELECT 1 FROM records r JOIN stores s ON s.id=r.store_id JOIN projects p ON p.id=s.project_id WHERE r.id=d.record_id AND r.archived_at IS NULL AND s.archived_at IS NULL AND p.archived_at IS NULL)`);await client.query("DELETE FROM fabric_semantic_documents s WHERE NOT EXISTS(SELECT 1 FROM fabric_search_documents d WHERE d.record_id=s.record_id)");await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
    async search(query:string,terms:string[],projectIds:string[]|undefined,limit:number,sourceTypes?:string[]){await this.synchronize(); const values:unknown[]=[query,terms.join(" | "),limit,terms]; let project=""; if(projectIds?.length){values.push(projectIds);project=`AND d.project_id=ANY($${values.length}::uuid[])`;}let sources="AND d.source_type NOT IN ('portfolio-draft','contentful-portfolio')";if(sourceTypes?.length){values.push(sourceTypes);sources=`AND d.source_type=ANY($${values.length}::text[])`;}
      // Query-local inverse document frequency prevents ubiquitous store names and
      // repeated words from burying the one record that names the requested entity.
      const result=await this.pool.query(`WITH scoped AS (
        SELECT d.* FROM fabric_search_documents d WHERE true ${project} ${sources}
      ), matches AS (
        SELECT d.record_id,term FROM scoped d CROSS JOIN unnest($4::text[]) term
        WHERE CASE WHEN length(term)<=2
          THEN lower(d.searchable_text) ~ ('(^|[^[:alnum:]])'||term||'([^[:alnum:]]|$)')
          ELSE position(term in lower(d.searchable_text))>0 OR to_tsvector('english',d.searchable_text) @@ plainto_tsquery('english',term) END
      ), weights AS (
        SELECT term,ln(1.0+(SELECT count(*) FROM scoped)/(1.0+(SELECT count(*) FROM matches m WHERE m.term=t.term))) AS weight
        FROM unnest($4::text[]) t(term)
      ), candidates AS (
        SELECT d.*,ts_rank_cd(d.search_vector,to_tsquery('simple',$2)) AS text_rank,
          count(*)::float/cardinality($4::text[]) AS term_coverage,count(*)::int AS matched_term_count,
          sum(w.weight)/(SELECT sum(weight) FROM weights) AS weighted_coverage,
          position(lower($1) in lower(d.searchable_text))>0 AS exact_phrase
        FROM scoped d JOIN matches m ON m.record_id=d.record_id JOIN weights w ON w.term=m.term
        GROUP BY d.record_id,d.project_id,d.store_id,d.project_name,d.store_name,d.field_text,d.searchable_text,d.display_text,d.source_updated_at,d.indexed_at,d.search_vector,d.source_type,d.source_id,d.record_data,d.record_created_at,d.record_updated_at
      ), ranked AS (
        SELECT c.*,2*weighted_coverage+0.2*text_rank/(1+text_rank)+CASE WHEN exact_phrase THEN 0.5 ELSE 0 END AS lexical_score FROM candidates c
      ) SELECT c.project_id,c.project_name,c.store_id,c.store_name,
        jsonb_build_object('id',c.record_id,'projectId',c.project_id,'storeId',c.store_id,'data',c.record_data,'createdAt',to_char(c.record_created_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'updatedAt',to_char(c.record_updated_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')) AS record,
        c.text_rank,c.term_coverage,c.matched_term_count,c.exact_phrase,c.lexical_score,count(*) OVER()::int candidate_count
        FROM ranked c
        ORDER BY c.lexical_score DESC,c.project_id,c.store_id,c.record_id LIMIT $3`,values);
      return result.rows as SearchRow[];
    }
    async scope(projectIds?:string[],sourceTypes?:string[]){await this.synchronize();const values:unknown[]=[];const where=["source_type NOT IN ('portfolio-draft','contentful-portfolio')"];if(projectIds?.length){values.push(projectIds);where.push(`project_id=ANY($${values.length}::uuid[])`);}if(sourceTypes?.length){values.push(sourceTypes);where.splice(0,1,`source_type=ANY($${values.length}::text[])`);}const result=await this.pool.query(`SELECT count(DISTINCT project_id)::int projects,count(DISTINCT store_id)::int stores FROM fabric_search_documents WHERE ${where.join(" AND ")}`,values);return result.rows[0] as {projects:number;stores:number};}
    async semanticIndexWork(model:string):Promise<SemanticIndexWork[]>{const result=await this.pool.query(`SELECT d.record_id AS "recordId",d.field_text AS text,d.source_updated_at AS "sourceUpdatedAt" FROM fabric_search_documents d LEFT JOIN fabric_semantic_documents s ON s.record_id=d.record_id WHERE d.source_type NOT IN ('portfolio-draft','contentful-portfolio') AND (s.record_id IS NULL OR s.model<>$1 OR s.semantic_text<>d.field_text OR s.source_updated_at<>d.source_updated_at) ORDER BY d.record_id`,[model]);return result.rows;}
    async upsertSemantic(model:string,items:{recordId:string;text:string;sourceUpdatedAt:string;embedding:number[]}[]){if(!items.length)return;const client=await this.pool.connect();try{await client.query("BEGIN");for(const item of items)await client.query(`INSERT INTO fabric_semantic_documents(record_id,model,semantic_text,embedding,dimension,source_updated_at,indexed_at) VALUES($1,$2,$3,$4,$5,$6,now()) ON CONFLICT(record_id) DO UPDATE SET model=excluded.model,semantic_text=excluded.semantic_text,embedding=excluded.embedding,dimension=excluded.dimension,source_updated_at=excluded.source_updated_at,indexed_at=now()`,[item.recordId,model,item.text,item.embedding,item.embedding.length,item.sourceUpdatedAt]);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
    async semanticSearch(model:string,embedding:number[],projectIds:string[]|undefined,limit:number,sourceTypes?:string[]){const values:unknown[]=[model,embedding,limit,0.35];let project="";if(projectIds?.length){values.push(projectIds);project=`AND d.project_id=ANY($${values.length}::uuid[])`;}let sources="AND d.source_type NOT IN ('portfolio-draft','contentful-portfolio')";if(sourceTypes?.length){values.push(sourceTypes);sources=`AND d.source_type=ANY($${values.length}::text[])`;}const result=await this.pool.query(`WITH candidates AS(SELECT d.*,fabric_cosine_similarity(s.embedding,$2::double precision[]) AS semantic_similarity FROM fabric_semantic_documents s JOIN fabric_search_documents d ON d.record_id=s.record_id WHERE s.model=$1 AND s.dimension=cardinality($2::double precision[]) ${project} ${sources}) SELECT c.project_id,c.project_name,c.store_id,c.store_name,jsonb_build_object('id',c.record_id,'projectId',c.project_id,'storeId',c.store_id,'data',c.record_data,'createdAt',to_char(c.record_created_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'updatedAt',to_char(c.record_updated_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')) AS record,c.semantic_similarity,count(*) OVER()::int candidate_count FROM candidates c WHERE c.semantic_similarity >= $4 ORDER BY c.semantic_similarity DESC,c.project_id,c.store_id,c.record_id LIMIT $3`,values);return result.rows as SemanticRow[];}
    async replaceExternalDocuments(sourceType:string,documents:ExternalFabricDocument[]){const client=await this.pool.connect();try{await client.query("BEGIN");await client.query("SELECT pg_advisory_xact_lock($1)",[0x434f4e54]);const ids:string[]=[];for(const document of documents){ids.push(document.sourceId);await client.query(`INSERT INTO fabric_search_documents(record_id,project_id,store_id,project_name,store_name,field_text,searchable_text,display_text,source_updated_at,indexed_at,source_type,source_id,record_data,record_created_at,record_updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,now(),$10,$11,$12,$13,$14) ON CONFLICT(record_id) DO UPDATE SET project_id=excluded.project_id,store_id=excluded.store_id,project_name=excluded.project_name,store_name=excluded.store_name,field_text=excluded.field_text,searchable_text=excluded.searchable_text,display_text=excluded.display_text,source_updated_at=excluded.source_updated_at,indexed_at=now(),source_type=excluded.source_type,source_id=excluded.source_id,record_data=excluded.record_data,record_created_at=excluded.record_created_at,record_updated_at=excluded.record_updated_at`,[document.recordId,document.projectId,document.storeId,document.projectName,document.storeName,document.fieldText,document.searchableText,document.displayText,document.updatedAt,sourceType,document.sourceId,document.data,document.createdAt,document.updatedAt]);}await client.query(`DELETE FROM fabric_search_documents WHERE source_type=$1 AND NOT (source_id=ANY($2::text[]))`,[sourceType,ids]);await client.query("DELETE FROM fabric_semantic_documents s WHERE NOT EXISTS(SELECT 1 FROM fabric_search_documents d WHERE d.record_id=s.record_id)");await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
    async clearSemanticIndex(){await this.pool.query("TRUNCATE fabric_semantic_documents");}
    async authorityPolicies(storeIds:string[],recordIds:string[]){if(!storeIds.length)return {stores:[] as StoreAuthorityPolicy[],records:[] as RecordAuthorityPolicy[]};const [stores,records]=await Promise.all([this.pool.query(`SELECT store_id AS "storeId",authority_role AS "authorityRole",canonical_store_id AS "canonicalStoreId",equivalence_kind AS "equivalenceKind",identity_fields AS "identityFields",comparison_fields AS "comparisonFields",effective_time_fields AS "effectiveTimeFields",current_field AS "currentField",current_values AS "currentValues",historical_values AS "historicalValues",note FROM fabric_store_authority_policies WHERE store_id=ANY($1::uuid[])`,[storeIds]),this.pool.query(`SELECT record_id AS "recordId",authority_role AS "authorityRole",effective_at AS "effectiveAt",supersedes_record_id AS "supersedesRecordId",note FROM fabric_record_authority_policies WHERE record_id=ANY($1::uuid[])`,[recordIds])]);return {stores:stores.rows as StoreAuthorityPolicy[],records:records.rows.map((row)=>({...row,...(row.effectiveAt&&{effectiveAt:new Date(row.effectiveAt).toISOString()})})) as RecordAuthorityPolicy[]};}
    async setStoreAuthorityPolicy(policy:StoreAuthorityPolicy){await this.pool.query(`INSERT INTO fabric_store_authority_policies(store_id,authority_role,canonical_store_id,equivalence_kind,identity_fields,comparison_fields,effective_time_fields,current_field,current_values,historical_values,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(store_id) DO UPDATE SET authority_role=excluded.authority_role,canonical_store_id=excluded.canonical_store_id,equivalence_kind=excluded.equivalence_kind,identity_fields=excluded.identity_fields,comparison_fields=excluded.comparison_fields,effective_time_fields=excluded.effective_time_fields,current_field=excluded.current_field,current_values=excluded.current_values,historical_values=excluded.historical_values,note=excluded.note,updated_at=now()`,[policy.storeId,policy.authorityRole,policy.canonicalStoreId??null,policy.equivalenceKind,policy.identityFields,policy.comparisonFields,policy.effectiveTimeFields,policy.currentField??null,policy.currentValues,policy.historicalValues,policy.note??null]);}
    async setRecordAuthorityPolicy(policy:RecordAuthorityPolicy){await this.pool.query(`INSERT INTO fabric_record_authority_policies(record_id,authority_role,effective_at,supersedes_record_id,note) VALUES($1,$2,$3,$4,$5) ON CONFLICT(record_id) DO UPDATE SET authority_role=excluded.authority_role,effective_at=excluded.effective_at,supersedes_record_id=excluded.supersedes_record_id,note=excluded.note,updated_at=now()`,[policy.recordId,policy.authorityRole??null,policy.effectiveAt??null,policy.supersedesRecordId??null,policy.note??null]);}
}
