import {AtlasError} from "../catalog.js";
import type {EmbeddingProvider} from "./embeddings.js";
import {projectRecord,queryTerms} from "./projection.js";
import {FabricSearchRepository,type SearchRow,type SemanticRow} from "./repository.js";
import type {FabricResult,RetrievalMode,SearchResponse} from "./types.js";

const termMatches=(text:string,term:string)=>term.length<=2?new RegExp(`(^|[^\\p{L}\\p{N}])${term}([^\\p{L}\\p{N}]|$)`,"iu").test(text):text.includes(term);
const clamp=(value:number)=>Math.min(Math.max(value,0),1);
const tie=(a:FabricResult,b:FabricResult)=>a.project.id.localeCompare(b.project.id)||a.store.id.localeCompare(b.store.id)||a.record.id.localeCompare(b.record.id);

export class FabricSearchService{
 constructor(readonly repository:FabricSearchRepository,readonly embeddingProvider:EmbeddingProvider|null=null){}
 async rebuildSemanticIndex(){await this.repository.clearSemanticIndex();}
 private lexicalResult(row:SearchRow,terms:string[]):FabricResult{
  const projection=projectRecord(row.record.data);const matchedFields=projection.fields.filter((field)=>terms.some((term)=>termMatches(field.searchText.toLocaleLowerCase(),term))).map((field)=>field.path);const lower=projection.searchableText.toLocaleLowerCase();const metadata=`${row.project_name} ${row.store_name}`.toLocaleLowerCase();const matchedTermCount=terms.filter((term)=>termMatches(lower,term)||termMatches(metadata,term)).length;const lexicalScore=Number((row.text_rank+Number(row.term_coverage)+(row.exact_phrase?1:0)).toFixed(6));const reasons=[...(row.exact_phrase?["exact phrase match"]:[]),...(row.text_rank>0?["PostgreSQL full-text term match"]:[]),...(Number(row.term_coverage)>0?[terms.some((term)=>term.length<=2)?"token-boundary term coverage":"substring term coverage"]:[]),...(matchedFields.length?[`matching fields: ${matchedFields.join(", ")}`]:[])];return {project:{id:row.project_id,name:row.project_name},store:{id:row.store_id,name:row.store_name},record:row.record,score:lexicalScore,matchedFields,snippet:projection.displayText.slice(0,320),reasons,projection:{searchableFields:projection.searchableFields,displayOnlyFields:projection.displayOnlyFields},ranking:{textRank:row.text_rank,termCoverage:Number(row.term_coverage),exactPhrase:row.exact_phrase,matchedTermCount,lexicalFound:true,semanticFound:false,lexicalScore,lexicalNormalized:0,lexicalRank:null,lexicalContribution:0,semanticSimilarity:null,semanticScore:0,semanticRank:null,semanticContribution:0,hybridScore:lexicalScore,tieBreak:{projectId:row.project_id,storeId:row.store_id,recordId:row.record.id}}};
 }
 private semanticResult(row:SemanticRow):FabricResult{const projection=projectRecord(row.record.data);const similarity=Number(row.semantic_similarity);const semanticScore=clamp((similarity+1)/2);return {project:{id:row.project_id,name:row.project_name},store:{id:row.store_id,name:row.store_name},record:row.record,score:semanticScore,matchedFields:[],snippet:projection.displayText.slice(0,320),reasons:["semantic embedding similarity"],projection:{searchableFields:projection.searchableFields,displayOnlyFields:projection.displayOnlyFields},ranking:{textRank:0,termCoverage:0,exactPhrase:false,matchedTermCount:0,lexicalFound:false,semanticFound:true,lexicalScore:0,lexicalNormalized:0,lexicalRank:null,lexicalContribution:0,semanticSimilarity:similarity,semanticScore,semanticRank:null,semanticContribution:0,hybridScore:semanticScore,tieBreak:{projectId:row.project_id,storeId:row.store_id,recordId:row.record.id}}};}
 private async indexSemantic(){if(!this.embeddingProvider)throw new Error("Semantic retrieval is disabled.");await this.repository.synchronize();const work=await this.repository.semanticIndexWork(this.embeddingProvider.model);if(!work.length)return;const vectors=await this.embeddingProvider.embed(work.map((item)=>item.text));if(vectors.length!==work.length)throw new Error("Embedding provider returned the wrong number of vectors.");const dimension=vectors[0]?.length??0;if(!dimension||vectors.some((vector)=>vector.length!==dimension||vector.some((value)=>!Number.isFinite(value))))throw new Error("Embedding provider returned invalid or inconsistent vectors.");await this.repository.upsertSemantic(this.embeddingProvider.model,work.map((item,index)=>({...item,embedding:vectors[index]!})));}
 async search(input:{query:string;projectIds?:string[];limit?:number;mode?:RetrievalMode}):Promise<SearchResponse>{
  const query=input.query.trim();if(!query)throw new AtlasError("Search query cannot be empty.");const terms=queryTerms(query);const mode=input.mode??"hybrid";const limit=Math.min(Math.max(input.limit??20,1),100);const scope=await this.repository.scope(input.projectIds);const empty=(semanticStatus:"ready"|"disabled"|"unavailable",semanticError?:string):SearchResponse=>({query,results:[],diagnostics:{searchedProjects:scope.projects,searchedStores:scope.stores,candidateCount:0,lexicalCandidateCount:0,semanticCandidateCount:0,returnedCount:0,terms,mode,embeddingModel:this.embeddingProvider?.model??null,semanticStatus,...(semanticError&&{semanticError}),indexConsistency:"synchronous-on-read"}});if(!terms.length)return empty(this.embeddingProvider?"ready":"disabled");
  let lexicalResults:FabricResult[]=[];let lexicalCandidateCount=0;if(mode!=="semantic"){const rows=await this.repository.search(query,terms,input.projectIds,mode==="lexical"?limit:100);lexicalCandidateCount=rows[0]?.candidate_count??0;lexicalResults=rows.map((row)=>this.lexicalResult(row,terms));if(mode==="lexical")return {query,results:lexicalResults,diagnostics:{...empty(this.embeddingProvider?"ready":"disabled").diagnostics,candidateCount:lexicalCandidateCount,lexicalCandidateCount,returnedCount:lexicalResults.length}};}
  if(!this.embeddingProvider){const fallback=lexicalResults.slice(0,limit);return {query,results:fallback,diagnostics:{...empty("disabled").diagnostics,candidateCount:lexicalCandidateCount,lexicalCandidateCount,returnedCount:fallback.length}};}
  let semanticRows:SemanticRow[]=[];try{await this.indexSemantic();const [queryVector]=await this.embeddingProvider.embed([query]);if(!queryVector?.length||queryVector.some((value)=>!Number.isFinite(value)))throw new Error("Embedding provider returned an invalid query vector.");semanticRows=await this.repository.semanticSearch(this.embeddingProvider.model,queryVector,input.projectIds,100);}catch(error){const message=error instanceof Error?error.message:String(error);if(mode==="semantic")return empty("unavailable",message);const fallback=lexicalResults.slice(0,limit);return {query,results:fallback,diagnostics:{...empty("unavailable",message).diagnostics,candidateCount:lexicalCandidateCount,lexicalCandidateCount,returnedCount:fallback.length}};}
  const semanticResults=semanticRows.map((row)=>this.semanticResult(row));if(mode==="semantic"){const results=semanticResults.slice(0,limit);return {query,results,diagnostics:{...empty("ready").diagnostics,candidateCount:semanticRows[0]?.candidate_count??0,semanticCandidateCount:semanticRows[0]?.candidate_count??0,returnedCount:results.length}};}
  const maximumLexical=Math.max(...lexicalResults.map((result)=>result.ranking.lexicalScore),0);const merged=new Map<string,FabricResult>();for(const [index,result] of lexicalResults.entries()){result.ranking.lexicalNormalized=maximumLexical?result.ranking.lexicalScore/maximumLexical:0;result.ranking.lexicalRank=index+1;result.ranking.lexicalContribution=0.45/(index+1);result.ranking.hybridScore=result.ranking.lexicalContribution;result.score=result.ranking.hybridScore;merged.set(result.record.id,result);}for(const [index,semantic] of semanticResults.entries()){const semanticRank=index+1,semanticContribution=0.55/semanticRank;const existing=merged.get(semantic.record.id);if(existing){existing.ranking.semanticFound=true;existing.ranking.semanticSimilarity=semantic.ranking.semanticSimilarity;existing.ranking.semanticScore=semantic.ranking.semanticScore;existing.ranking.semanticRank=semanticRank;existing.ranking.semanticContribution=semanticContribution;existing.ranking.hybridScore=existing.ranking.lexicalContribution+semanticContribution;existing.score=Number(existing.ranking.hybridScore.toFixed(6));existing.reasons.push("semantic embedding similarity");}else{semantic.ranking.semanticRank=semanticRank;semantic.ranking.semanticContribution=semanticContribution;semantic.ranking.hybridScore=semanticContribution;semantic.score=Number(semantic.ranking.hybridScore.toFixed(6));merged.set(semantic.record.id,semantic);}}
  const results=[...merged.values()].sort((a,b)=>b.ranking.hybridScore-a.ranking.hybridScore||b.ranking.semanticScore-a.ranking.semanticScore||b.ranking.lexicalNormalized-a.ranking.lexicalNormalized||tie(a,b)).slice(0,limit);const semanticCandidateCount=semanticRows[0]?.candidate_count??0;return {query,results,diagnostics:{...empty("ready").diagnostics,candidateCount:merged.size,lexicalCandidateCount,semanticCandidateCount,returnedCount:results.length}};
 }
}
