import type { AtlasRecord } from "../types.js";
export type RetrievalMode="lexical"|"semantic"|"hybrid";
export type RetrievalResult={project:{id:string;name:string};store:{id:string;name:string};record:AtlasRecord;score:number;matchedFields:string[];snippet:string;reasons:string[];projection:{searchableFields:string[];displayOnlyFields:{path:string;reason:string}[]};ranking:{textRank:number;termCoverage:number;exactPhrase:boolean;matchedTermCount:number;lexicalFound:boolean;semanticFound:boolean;lexicalScore:number;lexicalNormalized:number;lexicalRank:number|null;lexicalContribution:number;semanticSimilarity:number|null;semanticScore:number;semanticRank:number|null;semanticContribution:number;hybridScore:number;tieBreak:{projectId:string;storeId:string;recordId:string}}};
export type SearchResponse={query:string;results:RetrievalResult[];diagnostics:{searchedProjects:number;searchedStores:number;candidateCount:number;lexicalCandidateCount:number;semanticCandidateCount:number;returnedCount:number;terms:string[];mode:RetrievalMode;embeddingModel:string|null;semanticStatus:"ready"|"disabled"|"unavailable";semanticError?:string;indexConsistency:"synchronous-on-read"}};
export type ContextResponse={query:string;selections:RetrievalResult[];diagnostics:{searchedProjects:number;searchedStores:number;candidateCount:number;selectedCount:number;maxRecords:number;truncated?:boolean;semanticStatus?:"ready"|"disabled"|"unavailable";semanticError?:string;relevanceFloorRejected:number;authorityStatus:"ready"|"unavailable";authorityError?:string;authorityDecisions:AuthorityDecision[];authoritySuppressed:number;unresolvedConflicts:number;redundancyRejected:number;diversification:{droppedRecordId:string;keptRecordId:string;overlap:number;reason:string}[]}};
export type AuthorityRole="canonical"|"primary"|"mirror"|"derived"|"historical"|"supporting"|"unknown";
export type AuthorityDecision={equivalenceGroupId:string;equivalenceKind:"same_entity"|"same_fact";identity:unknown[];records:{recordId:string;authorityRole:AuthorityRole;relation:AuthorityRole;currentness:"current"|"historical"|"unknown";effectiveAt:string|null;conflictsWith:string[]}[];preferredRecordId?:string;suppressedRecordIds:string[];reason:string;contradictionStatus:"none"|"resolved"|"unresolved";unresolvedAmbiguity:boolean};

/** Legacy diagnostic type name retained for existing debug clients. */
export type FabricResult = RetrievalResult;
