import { useCallback, useEffect, useMemo, useState } from "react";
import { API_BASE, callTool } from "./api";
import "./Portfolio.css";

type ContentType = "profile" | "contact" | "projects" | "experience" | "posts" | "collections";
type Field = { name:string; type:"string"|"number"|"boolean"|"date"|"datetime"|"enum"|"array"|"object"; enumValues?:string[]; description?:string };
type Schema = { contentType:ContentType; storeId:string; name:string; description?:string; fields:Field[] };
type Entry = { id:string; contentType:ContentType; storeId:string; data:Record<string,unknown>; status:"draft"|"published"|"changed"; createdAt:string; updatedAt:string; publishedAt?:string; publishedRevision?:number };
type Dashboard = { contentTypes:{contentType:ContentType;storeId:string;name:string;total:number;published:number;drafts:number}[];media:{active:number;bytes:number} };
type Media = { id:string;originalName:string;mimeType:string;byteSize:number;width?:number;height?:number;altText?:string;caption?:string;status:string;url:string;thumbnailUrl?:string;previewUrl?:string };
type Revision = {id:string;revision:number;createdBy:string;createdAt:string;published:boolean};

const TITLES:Record<ContentType,string>={profile:"Profile",contact:"Contact",projects:"Projects",experience:"Experience",posts:"Posts",collections:"Collections"};
const LONG_FIELDS=new Set(["description","summary","body","excerpt","note","tagline"]);
const label=(value:string)=>value.replace(/([a-z])([A-Z])/g,"$1 $2").replace(/^./,x=>x.toUpperCase());
const formatBytes=(value:number)=>value<1024?`${value} B`:value<1024*1024?`${(value/1024).toFixed(1)} KB`:`${(value/1024/1024).toFixed(1)} MB`;
const entryTitle=(entry:Entry)=>String(entry.data.title||entry.data.company||[entry.data.firstName,entry.data.lastName].filter(Boolean).join(" ")||entry.data.email||entry.data.key||"Untitled draft");

export function Portfolio(){
 const [schemas,setSchemas]=useState<Schema[]>([]),[entries,setEntries]=useState<Entry[]>([]),[dashboard,setDashboard]=useState<Dashboard>(),[media,setMedia]=useState<Media[]>([]);
 const [type,setType]=useState<ContentType>("projects"),[selectedId,setSelectedId]=useState<string>(),[draft,setDraft]=useState<Record<string,unknown>>({}),[view,setView]=useState<"content"|"media">("content"),[revisions,setRevisions]=useState<Revision[]>([]);
 const [busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{try{const [s,e,d,m]=await Promise.all([callTool<Schema[]>("get_portfolio_schemas",{}),callTool<Entry[]>("list_portfolio_entries",{}),callTool<Dashboard>("get_portfolio_dashboard",{}),callTool<Media[]>("list_portfolio_media",{})]);setSchemas(s);setEntries(e);setDashboard(d);setMedia(m);setError("");}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{void load();},[load]);
 const filtered=useMemo(()=>entries.filter(entry=>entry.contentType===type),[entries,type]);
 const selected=entries.find(entry=>entry.id===selectedId);
 useEffect(()=>{if(selected){setDraft(selected.data);void callTool<Revision[]>("list_portfolio_revisions",{recordId:selected.id}).then(setRevisions).catch(()=>setRevisions([]));}else{setDraft({});setRevisions([]);}},[selectedId,selected?.updatedAt]);
 useEffect(()=>{if(selectedId&&!filtered.some(x=>x.id===selectedId))setSelectedId(undefined);},[type,filtered,selectedId]);
 const schema=schemas.find(item=>item.contentType===type);
 const run=async(name:string,action:()=>Promise<unknown>,message:string)=>{setBusy(name);setError("");setNotice("");try{await action();await load();setNotice(message);}catch(e){setError((e as Error).message);}finally{setBusy("");}};
 const save=async()=>{setBusy("save");setError("");try{const entry=await callTool<Entry>("save_portfolio_draft",{contentType:type,recordId:selectedId,data:draft});setSelectedId(entry.id);await load();setNotice("Draft saved. Nothing has been published yet.");}catch(e){setError((e as Error).message);}finally{setBusy("");}};
 const change=(field:Field,value:unknown)=>setDraft(current=>({...current,[field.name]:value}));
 return <div className="portfolio-app"><header className="portfolio-head"><div><p className="eyebrow">Atlas-native publishing</p><h1>Portfolio</h1><p>Draft, review, publish, and deliver the portfolio from one contained Atlas project.</p></div><div className="portfolio-summary"><span><b>{entries.length}</b> entries</span><span><b>{entries.filter(x=>x.status==="published").length}</b> published</span><span><b>{dashboard?.media.active??0}</b> media</span></div></header>
 <nav className="portfolio-tabs"><button className={view==="content"?"active":""} onClick={()=>setView("content")}>Content</button><button className={view==="media"?"active":""} onClick={()=>setView("media")}>Media library</button><a href="#/ask-portfolio">Open Ask Portfolio ↗</a></nav>
 {error&&<div className="notice error">{error}</div>}{notice&&<div className="notice success">{notice}</div>}
 {view==="content"?<div className="portfolio-workspace"><aside className="portfolio-types"><p className="section-label">Content types</p>{(Object.keys(TITLES) as ContentType[]).map(key=>{const counts=dashboard?.contentTypes.find(x=>x.contentType===key);return <button key={key} className={type===key?"active":""} onClick={()=>setType(key)}><span>{TITLES[key]}</span><small>{counts?.published??0}/{counts?.total??0} live</small></button>;})}</aside>
 <section className="portfolio-entries"><div className="portfolio-panel-head"><div><p className="eyebrow">{TITLES[type]}</p><h2>Entries</h2></div><button onClick={()=>{setSelectedId(undefined);setDraft({});}}>New</button></div>{filtered.map(entry=><button key={entry.id} className={`portfolio-entry ${selectedId===entry.id?"active":""}`} onClick={()=>setSelectedId(entry.id)}><span><b>{entryTitle(entry)}</b><small>Updated {new Date(entry.updatedAt).toLocaleDateString()}</small></span><i className={`portfolio-status ${entry.status}`}>{entry.status}</i></button>)}{!filtered.length&&<p className="portfolio-empty">No {TITLES[type].toLowerCase()} yet.</p>}</section>
 <section className="portfolio-editor"><div className="portfolio-panel-head"><div><p className="eyebrow">{selected?"Edit draft":"New draft"}</p><h2>{selected?entryTitle(selected):TITLES[type]}</h2></div>{selected&&<i className={`portfolio-status ${selected.status}`}>{selected.status}</i>}</div><div className="portfolio-form">{schema?.fields.map(field=><EditorField key={field.name} field={field} value={draft[field.name]} media={media} onChange={value=>change(field,value)}/>)}</div><div className="portfolio-editor-actions"><button className="ghost" disabled={!selected||!!busy} onClick={()=>selected&&run("archive",()=>callTool("archive_portfolio_entry",{recordId:selected.id}),"Entry archived.").then(()=>setSelectedId(undefined))}>Archive</button>{selected&&selected.status!=="draft"&&<button className="ghost" disabled={!!busy} onClick={()=>run("unpublish",()=>callTool("unpublish_portfolio_entry",{recordId:selected.id}),"Entry unpublished; its draft is intact.")}>Unpublish</button>}<span/><button className="ghost" disabled={!!busy} onClick={save}>{busy==="save"?"Saving…":"Save draft"}</button><button disabled={!selected||!!busy} onClick={()=>selected&&run("publish",()=>callTool("publish_portfolio_entry",{recordId:selected.id}),"A new immutable revision is live.")}>{busy==="publish"?"Publishing…":"Publish"}</button></div>{selected&&<details className="portfolio-revisions"><summary>Revision history ({revisions.length})</summary>{revisions.map(revision=><div key={revision.id}><span><b>Revision {revision.revision}</b><small>{new Date(revision.createdAt).toLocaleString()} · {revision.createdBy}</small></span>{revision.published?<i>Live</i>:<button className="link" onClick={()=>run("restore",()=>callTool("restore_portfolio_revision",{recordId:selected.id,revisionId:revision.id}),`Revision ${revision.revision} restored to draft.`)}>Restore to draft</button>}</div>)}</details>}</section></div>:<MediaLibrary media={media} busy={busy} setBusy={setBusy} setError={setError} setNotice={setNotice} reload={load}/>}</div>;
}

function EditorField({field,value,media,onChange}:{field:Field;value:unknown;media:Media[];onChange:(value:unknown)=>void}){
 const asset=field.name.endsWith("AssetId");
 if(asset)return <label>{label(field.name.replace(/Id$/, ""))}<select value={String(value??"")} onChange={e=>onChange(e.target.value)}><option value="">No asset</option>{media.filter(x=>x.status==="active").map(item=><option key={item.id} value={item.id}>{item.originalName}{item.altText?` — ${item.altText}`:""}</option>)}</select></label>;
 if(field.type==="boolean")return <label className="portfolio-check"><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/>{label(field.name)}</label>;
 if(field.type==="enum")return <label>{label(field.name)}<select value={String(value??"")} onChange={e=>onChange(e.target.value)}><option value="">Select…</option>{field.enumValues?.map(option=><option key={option}>{option}</option>)}</select></label>;
 if(field.type==="array"||field.type==="object")return <label>{label(field.name)}<textarea value={value===undefined?"":typeof value==="string"?value:JSON.stringify(value,null,2)} onChange={e=>{try{onChange(JSON.parse(e.target.value||(field.type==="array"?"[]":"{}")));}catch{onChange(e.target.value);}}} placeholder={field.type==="array"?'["First item"]':'{"label":"value"}'}/><small>JSON {field.type}</small></label>;
 if(LONG_FIELDS.has(field.name))return <label>{label(field.name)}<textarea className={field.name==="body"?"portfolio-body":""} value={String(value??"")} onChange={e=>onChange(e.target.value)}/>{field.name==="body"&&<small>Markdown supported</small>}</label>;
 return <label>{label(field.name)}<input type={field.type==="number"?"number":field.type==="datetime"?"datetime-local":"text"} value={String(value??"")} onChange={e=>onChange(field.type==="number"?(e.target.value===""?undefined:Number(e.target.value)):field.type==="datetime"&&e.target.value?new Date(e.target.value).toISOString():e.target.value)}/></label>;
}

function MediaLibrary({media,busy,setBusy,setError,setNotice,reload}:{media:Media[];busy:string;setBusy:(x:string)=>void;setError:(x:string)=>void;setNotice:(x:string)=>void;reload:()=>Promise<void>}){
 const [file,setFile]=useState<File>(),[alt,setAlt]=useState(""),[caption,setCaption]=useState("");
 const upload=async(e:React.FormEvent)=>{e.preventDefault();if(!file)return;setBusy("upload");setError("");try{const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]??"");reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});await callTool("upload_portfolio_media",{fileName:file.name,mimeType:file.type,base64,altText:alt,caption});await reload();setFile(undefined);setAlt("");setCaption("");setNotice("Media uploaded and image variants generated.");}catch(e){setError((e as Error).message);}finally{setBusy("");}};
 const update=async(asset:Media,values:Record<string,unknown>)=>{setBusy(asset.id);try{await callTool("update_portfolio_media",{assetId:asset.id,...values});await reload();setNotice("Media metadata updated.");}catch(e){setError((e as Error).message);}finally{setBusy("");}};
 return <div className="portfolio-media"><form className="portfolio-upload" onSubmit={upload}><div><p className="eyebrow">Upload</p><h2>Add an image or PDF</h2><p>Originals stay on Atlas storage; images get WebP thumbnail and preview variants.</p></div><label>File<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif,application/pdf" required onChange={e=>setFile(e.target.files?.[0])}/></label><label>Alt text<input value={alt} onChange={e=>setAlt(e.target.value)} placeholder="Describe the image"/></label><label>Caption<input value={caption} onChange={e=>setCaption(e.target.value)}/></label><button disabled={!file||busy==="upload"}>{busy==="upload"?"Uploading…":"Upload"}</button></form><div className="portfolio-media-grid">{media.map(asset=><article key={asset.id} className={asset.status==="archived"?"archived":""}>{asset.thumbnailUrl?<img src={`${API_BASE}${asset.thumbnailUrl}`} alt={asset.altText||""}/>:<div className="portfolio-pdf">PDF</div>}<div><b>{asset.originalName}</b><small>{formatBytes(asset.byteSize)}{asset.width?` · ${asset.width}×${asset.height}`:""}</small><label>Alt text<input defaultValue={asset.altText} onBlur={e=>{if(e.target.value!==asset.altText)void update(asset,{altText:e.target.value});}}/></label><label>Caption<input defaultValue={asset.caption} onBlur={e=>{if(e.target.value!==asset.caption)void update(asset,{caption:e.target.value});}}/></label><div><a href={`${API_BASE}${asset.url}`} target="_blank" rel="noreferrer">Open original</a><button className="link danger" disabled={busy===asset.id} onClick={()=>void update(asset,{status:asset.status==="active"?"archived":"active"})}>{asset.status==="active"?"Archive":"Restore"}</button></div></div></article>)}</div>{!media.length&&<p className="portfolio-empty">No media uploaded yet.</p>}</div>;
}
