import { themedViewDocument } from "./viewTheme";
import { ProjectNav } from "./AppShell";
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { installViewHost } from '@atlas/view-runtime/view-host';
import { callTool } from './api';
import { standaloneViewUrl } from './viewLinks';
import type { View, ViewRenderResult, AuditEvent, Store } from './types';
import { parameterHash, viewParams } from './viewBridge';
import './views.css';

type Draft={name:string;slug:string;actions:string;manifest:string;queries:string;html:string;css:string;script:string};
const blank:Draft={name:'Untitled View',slug:'',actions:'[]',manifest:JSON.stringify({viewKitVersion:1,capabilities:[]},null,2),queries:'[]',html:'<atlas-page>\n  <atlas-header title="My View" subtitle="Built with Atlas"></atlas-header>\n  <atlas-empty-state title="Start with your data">Add a Store query in Queries / Data.</atlas-empty-state>\n</atlas-page>',css:'',script:''};
const draftFrom=(v:View):Draft=>({name:v.name,slug:v.slug??'',actions:JSON.stringify(v.actions??[],null,2),manifest:JSON.stringify(v.manifest??null,null,2),queries:JSON.stringify(v.queries,null,2),html:v.html,css:v.css,script:v.script??''});
const definition=(draft:Draft)=>({name:draft.name,slug:draft.slug||null,actions:JSON.parse(draft.actions),manifest:JSON.parse(draft.manifest)||undefined,queries:JSON.parse(draft.queries),template:draft.html,css:draft.css,script:draft.script});

export function ViewFrame({rendered,preview=false,embedded=false,mobile=false,actionsEnabled=false,actionViewId,onRefresh,onError}:{rendered:ViewRenderResult;preview?:boolean;embedded?:boolean;mobile?:boolean;actionsEnabled?:boolean;actionViewId?:string;onRefresh?:(params:Record<string,string>)=>Promise<unknown>;onError?:(message:string)=>void}){
    const frame=useRef<HTMLIFrameElement>(null);
    useEffect(()=>{
        if(!frame.current)return;
        return installViewHost({frame:frame.current,runtimeId:rendered.runtimeId,params:rendered.manifest?.params??{},parameterCapability:!!rendered.manifest?.capabilities?.includes('url-params'),actionNames:(rendered.actions??[]).map(a=>a.name),actionsEnabled:actionsEnabled&&!!actionViewId&&!!rendered.manifest?.capabilities?.includes('record-actions'),
            onParam(key,value){if(!preview&&!embedded)history.replaceState(null,'',parameterHash(location.hash,key,value))},
            action(name,input){return callTool('execute_view_action',{projectId:rendered.view.projectId,viewId:actionViewId,action:name,input})},
            async refresh(params){if(!onRefresh)throw new Error('Refresh is unavailable.');return onRefresh(params)},onError});
    },[rendered,preview,embedded,actionsEnabled,actionViewId,onRefresh,onError]);
    const documentFrame=useMemo(()=><iframe ref={frame} title={preview&&!embedded?'Unsaved View preview':rendered.view.name} sandbox={rendered.manifest?"allow-scripts allow-popups allow-popups-to-escape-sandbox":"allow-popups allow-popups-to-escape-sandbox"} referrerPolicy="no-referrer" allow="camera 'none'; microphone 'none'; geolocation 'none'; clipboard-read 'none'; clipboard-write 'none'" srcDoc={themedViewDocument(rendered)}/>,[rendered.document,rendered.view.name,rendered.manifest,preview,embedded]);
    return <section className={`view-frame ${mobile?'view-mobile':''}`}>{documentFrame}</section>;
}

export function ViewPage({projectId,viewId}:{projectId:string;viewId:string}){
    const [previewActions,setPreviewActions]=useState(false);const isNew=viewId==='new';const [saved,setSaved]=useState<View>();const [draft,setDraft]=useState<Draft>(blank);const [rendered,setRendered]=useState<ViewRenderResult>();const editing=isNew||!saved?.archivedAt;const [tab,setTab]=useState<keyof Omit<Draft,'name'|'slug'>>('html');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [mobile,setMobile]=useState(false);const [revisions,setRevisions]=useState<AuditEvent[]>([]);const [stores,setStores]=useState<Store[]>([]);const [notice,setNotice]=useState('');const request=useRef(0);const [previewDraft,setPreviewDraft]=useState('');
    const load=async()=>{const id=++request.current;setBusy(true);setError('');setNotice('');setPreviewDraft('');setRendered(undefined);try{
        const list=await callTool<Store[]>('list_stores',{projectId});if(id!==request.current)return;setStores(list);
        if(!isNew){const v=await callTool<View>('get_view',{projectId,viewId,includeArchived:true});if(id!==request.current)return;setSaved(v);setDraft(draftFrom(v));const history=await callTool<AuditEvent[]>('get_view_history',{projectId,viewId});if(id!==request.current)return;setRevisions(history);/* The editor never opens a second full-sized live viewer. */}
    }catch(e){if(id===request.current)setError((e as Error).message)}finally{if(id===request.current)setBusy(false)}};
    useEffect(()=>{void load();return()=>{request.current++}},[projectId,viewId]);
    const preview=async()=>{const id=++request.current;setBusy(true);setError('');try{const parsed=definition(draft);const params=Object.fromEntries(Object.entries(viewParams()).filter(([key])=>Object.hasOwn(parsed.manifest?.params??{},key)));const result=await callTool<ViewRenderResult>('preview_view',{projectId,...parsed,params});if(id!==request.current)return;setRendered(result);setPreviewDraft(JSON.stringify(draft));setNotice('Preview updated. Changes are not saved.')}catch(e){if(id===request.current)setError((e as Error).message)}finally{if(id===request.current)setBusy(false)}};
    const save=async()=>{setBusy(true);setError('');try{const parsed=definition(draft);const result=await callTool<View>(isNew?'create_view':'update_view',{projectId,...(!isNew&&{viewId,expectedUpdatedAt:saved?.updatedAt}),...parsed,slug:parsed.slug??(isNew?undefined:null),manifest:parsed.manifest??null});setSaved(result);if(isNew){location.hash=`/projects/${projectId}/views/${result.id}`;return}await load();setNotice('View saved.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
    const dirty=JSON.stringify(draft)!==JSON.stringify(saved?draftFrom(saved):blank);
    useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(editing&&dirty){event.preventDefault();event.returnValue=''}};addEventListener('beforeunload',leave);return()=>removeEventListener('beforeunload',leave)},[editing,dirty]);
    const runtimeRefresh=useCallback(async(params:Record<string,string>)=>{const result=await callTool<ViewRenderResult>(editing?'preview_view':'render_view',editing?{projectId,...definition(draft),params}:{projectId,viewId,params});setRendered(result);setError('');return result},[editing,draft,projectId,viewId]);
    return <>
        <div className="breadcrumbs"><a href="#/projects">Projects</a><span>/</span><a href={`#/projects/${projectId}`}>Project</a><span>/</span><b>{saved?.name??'New View'}</b></div>
        <header className="page-head"><div><p className="eyebrow">View definition</p><h1>{saved?.name??'Create a View'}</h1><p>Edit and preview the View here. The live View opens in its own tab for full interaction.</p></div><div className="actions">{saved&&!saved.archivedAt&&<a className="view-open" href={standaloneViewUrl(saved)} target="_blank" rel="noopener noreferrer">Open in new tab ↗</a>}{editing&&<><button disabled={busy||!draft.name.trim()} onClick={save}>Save View</button><button className="ghost" disabled={busy} onClick={()=>{location.hash=`/projects/${projectId}/views`}}>Cancel</button></>}</div></header>
        <ProjectNav projectId={projectId} section="views" />
        {saved?.archivedAt&&<p className="notice">This View is archived. Its saved definition and history remain available below.</p>}
        {error&&<div role="alert" className="notice error">{error}</div>}{notice&&<p role="status" className="view-notice">{notice}</p>}{busy&&<p role="status">Loading View…</p>}
        {editing&&<section className="panel view-editor"><label>View name<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Standalone slug<input value={draft.slug} placeholder="my-view" onChange={e=>setDraft({...draft,slug:e.target.value})}/></label><div className="view-editor-tabs" role="tablist" aria-label="View source">{([['manifest','Manifest'],['queries','Queries / Data'],['actions','Actions'],['html','HTML'],['css','CSS'],['script','JavaScript']] as const).map(([key,label])=><button key={key} id={`editor-tab-${key}`} role="tab" aria-selected={tab===key} aria-controls="editor-panel" onClick={()=>setTab(key)}>{label}</button>)}</div><div id="editor-panel" role="tabpanel" aria-labelledby={`editor-tab-${tab}`}><label className="view-code-label">{tab==='html'?'Handlebars HTML template':tab==='script'?'Sandboxed JavaScript':tab==='queries'?'Saved Store queries (JSON)':tab==='manifest'?'Runtime manifest (JSON)':tab==='actions'?'Declared actions (JSON)':'View CSS'}<textarea spellCheck={false} className="view-code" value={draft[tab]} onChange={e=>setDraft({...draft,[tab]:e.target.value})}/></label></div>{tab==='queries'&&<details><summary>Available Stores and fields</summary>{stores.map(s=><div key={s.id}><b>{s.name}</b><code>{s.id}</code><p>{s.schema.fields.map(f=>`${f.name}: ${f.type}`).join(' · ')}</p></div>)}</details>}<div className="view-editor-actions"><button disabled={busy} onClick={preview}>Update preview</button><button className="ghost" disabled={busy||isNew} onClick={()=>void load()}>Reload saved version</button><span>{dirty?'Unsaved changes':'Saved version'} · {previewDraft!==JSON.stringify(draft)?'Preview may be out of date':'Preview is current'}</span></div>{saved&&<label className="toggle"><input type="checkbox" checked={previewActions} onChange={e=>setPreviewActions(e.target.checked)}/>Enable saved actions in preview (writes to Core)</label>}<p className="hint">Preview calls can only execute persisted actions. Save new declarations before testing them. Use Atlas components and --atlas-* tokens. Custom scripts require client-script. Declare URL parameters in the manifest. Preview parameters stay inside the preview.</p></section>}
        {rendered&&<><div className="view-preview-toolbar"><strong>{editing?'Unsaved preview':'Live data'}</strong><div><button aria-pressed={!mobile} onClick={()=>setMobile(false)}>Desktop</button><button aria-pressed={mobile} onClick={()=>setMobile(true)}>Mobile</button></div></div><ViewFrame rendered={rendered} preview={editing} mobile={mobile} actionsEnabled={!editing||previewActions} actionViewId={saved?.id} onRefresh={runtimeRefresh} onError={setError}/><details className="panel view-inspector"><summary>Query data · {rendered.diagnostics.queries.reduce((sum,q)=>sum+q.returned,0)} records</summary><pre>{JSON.stringify(rendered.data,null,2)}</pre></details></>}
        <details className="panel view-inspector"><summary>Declared actions · {saved?.actions?.length??0}</summary><pre>{JSON.stringify(saved?.actions??[],null,2)}</pre></details>{!isNew&&<details className="panel view-inspector"><summary>Revision history · {revisions.length} saved events</summary>{revisions.map(event=><details key={event.id}><summary>{new Date(event.occurredAt).toLocaleString()} · {event.operation} · {event.client}</summary><pre>{JSON.stringify(event.resulting,null,2)}</pre></details>)}<p className="hint">History retains full saved definitions, including manifest and JavaScript.</p></details>}
    </>;
}
