import "dotenv/config";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";
const client=new Client({name:"atlas-live-verifier",version:"2"}); await client.connect(new StreamableHTTPClientTransport(new URL(process.env.ATLAS_URL??"http://127.0.0.1:3000/mcp")));
const call=async(name,args={})=>{const response=await client.callTool({name,arguments:args}); if(response.isError) throw new Error(`${name}: ${response.content?.[0]?.text}`); return response.structuredContent.result;};
const project=(await call("list_projects")).find((x)=>x.name==="Launchpad"); if(!project) throw new Error("Launchpad was not imported.");
const store=(await call("list_stores",{projectId:project.id})).find((x)=>x.name==="Graduate Applications"); if(!store) throw new Error("Graduate Applications was not imported.");
const records=await call("query_records",{projectId:project.id,storeId:store.id,sort:[{field:"company",direction:"asc"}],limit:20,offset:0}); const lseg=records.items.find((x)=>x.data.company==="LSEG"); const macquarie=records.items.find((x)=>x.data.company==="Macquarie"); if(!lseg||!macquarie||lseg.data.oaStatus!=="completed") throw new Error("Imported application state is incomplete.");
const lsegAudit=await call("get_audit_history",{recordId:lseg.id});
const temporary=await call("create_record",{projectId:project.id,storeId:store.id,client:"postgres-live-verifier",data:{company:"Postgres Verification Temp",role:"Temporary",status:"active",stage:"verification",appliedAt:"2026-09-29",oaStatus:"pending"}});
const updated=await call("update_record",{projectId:project.id,storeId:store.id,recordId:temporary.id,client:"postgres-live-verifier",data:{oaStatus:"completed",oaCompletedAt:"2026-09-29"}}); const temporaryAudit=await call("get_audit_history",{recordId:temporary.id});
const before=(await call("list_records",{projectId:project.id,storeId:store.id})).total; let invalidBulkRejected=false; try{await call("bulk_records",{projectId:project.id,storeId:store.id,operations:[{action:"create",data:{company:"Would Roll Back",role:"Temporary",status:"active",stage:"verification",appliedAt:"2026-09-29",oaStatus:"pending"}},{action:"create",data:{company:"Invalid"}}]});}catch{invalidBulkRejected=true;} const after=(await call("list_records",{projectId:project.id,storeId:store.id})).total;
await call("archive_record",{projectId:project.id,storeId:store.id,recordId:temporary.id,client:"postgres-live-verifier"});
console.log(JSON.stringify({project:project.name,store:store.name,lseg:{id:lseg.id,oaStatus:lseg.data.oaStatus,auditEvents:lsegAudit.length},macquarie:{id:macquarie.id},query:{total:records.total,first:records.items[0]?.data.company},temporary:{stableId:temporary.id===updated.id,auditEvents:temporaryAudit.length,archived:true},invalidBulk:{rejected:invalidBulkRejected,noPartialCommit:before===after}},null,2)); await client.close();
import "dotenv/config";
