import { randomUUID } from "node:crypto";
import type { AtlasRepository } from "./store.js";
import type { AtlasData, AtlasRecord, AuditEvent, AuditOperation, FieldDefinition, Page, Project, RecordData, RecordFilter, SortSpec, Store } from "./types.js";

export class AtlasError extends Error { constructor(message: string, readonly code = "INVALID_REQUEST") { super(message); } }
type Client = { client?: string };
const now = () => new Date().toISOString();
const active = <T extends { archivedAt?: string }>(items: T[], includeArchived = false) => items.filter((item) => includeArchived || !item.archivedAt);
const cleanText = (value: string, label: string) => { const result = value.trim(); if (!result) throw new AtlasError(`${label} cannot be empty.`); return result; };

export class AtlasCatalog {
    constructor(readonly store: AtlasRepository) {}

    async status() { const data = await this.store.snapshot(); return { product: "Atlas", version: "2.0.0", storage: "postgresql", schemaVersion: data.schemaVersion, projects: active(data.projects).length, stores: active(data.stores).length, records: active(data.records).length }; }
    async listProjects(includeArchived = false) { return active((await this.store.snapshot()).projects, includeArchived); }
    async getProject(id: string, includeArchived = false) { return this.requireProject(await this.store.snapshot(), id, includeArchived); }
    async createProject(input: { name: string; description?: string } & Client) {
        return this.store.transaction((data) => { const name = cleanText(input.name, "Project name"); this.unique(data.projects, name, "project"); const stamp = now(); const project: Project = { id: randomUUID(), name, ...(input.description !== undefined && { description: input.description }), createdAt: stamp, updatedAt: stamp }; data.projects.push(project); this.audit(data, "project.created", input.client, project.id, undefined, undefined, undefined, project); return project; });
    }
    async updateProject(input: { projectId: string; name?: string; description?: string | null } & Client) {
        return this.store.transaction((data) => { const project = this.requireProject(data, input.projectId); const before = structuredClone(project); if (input.name !== undefined) { const name = cleanText(input.name, "Project name"); this.unique(data.projects, name, "project", project.id); project.name = name; } if (input.description !== undefined) input.description === null ? delete project.description : project.description = input.description; project.updatedAt = now(); this.audit(data, "project.updated", input.client, project.id, undefined, undefined, before, project); return project; });
    }
    async archiveProject(projectId: string, client?: string) {
        return this.store.transaction((data) => { const project = this.requireProject(data, projectId); const before = structuredClone(project); const stamp = now(); project.archivedAt = stamp; project.updatedAt = stamp; for (const store of data.stores.filter((x) => x.projectId === projectId && !x.archivedAt)) { store.archivedAt = stamp; store.updatedAt = stamp; } for (const record of data.records.filter((x) => x.projectId === projectId && !x.archivedAt)) { record.archivedAt = stamp; record.updatedAt = stamp; } this.audit(data, "project.archived", client, projectId, undefined, undefined, before, project); return project; });
    }

    async listStores(projectId: string, includeArchived = false) { const data = await this.store.snapshot(); this.requireProject(data, projectId, includeArchived); return active(data.stores.filter((x) => x.projectId === projectId), includeArchived); }
    async getStore(projectId: string, storeId: string, includeArchived = false) { const data = await this.store.snapshot(); this.requireProject(data, projectId, includeArchived); return this.requireStore(data, projectId, storeId, includeArchived); }
    async createStore(input: { projectId: string; name: string; description?: string; fields: FieldDefinition[] } & Client) {
        return this.store.transaction((data) => { this.requireProject(data, input.projectId); const name = cleanText(input.name, "Store name"); this.unique(data.stores.filter((x) => x.projectId === input.projectId), name, "store"); const fields = this.validateSchema(input.fields); const stamp = now(); const store: Store = { id: randomUUID(), projectId: input.projectId, name, ...(input.description !== undefined && { description: input.description }), schema: { version: 1, fields }, createdAt: stamp, updatedAt: stamp }; data.stores.push(store); this.audit(data, "store.created", input.client, input.projectId, store.id, undefined, undefined, store); return store; });
    }
    async updateStore(input: { projectId: string; storeId: string; name?: string; description?: string | null } & Client) {
        return this.store.transaction((data) => { const store = this.requireStore(data, input.projectId, input.storeId); const before = structuredClone(store); if (input.name !== undefined) { const name = cleanText(input.name, "Store name"); this.unique(data.stores.filter((x) => x.projectId === input.projectId), name, "store", store.id); store.name = name; } if (input.description !== undefined) input.description === null ? delete store.description : store.description = input.description; store.updatedAt = now(); this.audit(data, "store.updated", input.client, input.projectId, store.id, undefined, before, store); return store; });
    }
    async updateSchema(input: { projectId: string; storeId: string; fields: FieldDefinition[]; dropRemovedFields?: boolean } & Client) {
        return this.store.transaction((data) => { const store = this.requireStore(data, input.projectId, input.storeId); const before = structuredClone(store); const fields = this.validateSchema(input.fields); const names = new Set(fields.map((x) => x.name)); const records = data.records.filter((x) => x.storeId === store.id && !x.archivedAt); for (const record of records) { const candidate = structuredClone(record.data); for (const key of Object.keys(candidate)) if (!names.has(key)) { if (!input.dropRemovedFields) throw new AtlasError(`Schema removes field '${key}' used by existing records; set dropRemovedFields=true to remove it explicitly.`); delete candidate[key]; } record.data = this.validateRecord(fields, candidate); record.updatedAt = now(); } store.schema = { version: store.schema.version + 1, fields }; store.updatedAt = now(); this.audit(data, "store.schema_updated", input.client, input.projectId, store.id, undefined, before.schema, store.schema); return store; });
    }
    async archiveStore(projectId: string, storeId: string, client?: string) { return this.store.transaction((data) => { const store = this.requireStore(data, projectId, storeId); const before = structuredClone(store); const stamp = now(); store.archivedAt = stamp; store.updatedAt = stamp; for (const record of data.records.filter((x) => x.storeId === store.id && !x.archivedAt)) { record.archivedAt = stamp; record.updatedAt = stamp; } this.audit(data, "store.archived", client, projectId, storeId, undefined, before, store); return store; }); }

    async createRecord(input: { projectId: string; storeId: string; data: RecordData } & Client) { return this.store.transaction((state) => { const store = this.requireStore(state, input.projectId, input.storeId); const stamp = now(); const record: AtlasRecord = { id: randomUUID(), projectId: input.projectId, storeId: input.storeId, data: this.validateRecord(store.schema.fields, input.data), createdAt: stamp, updatedAt: stamp }; state.records.push(record); this.audit(state, "record.created", input.client, input.projectId, input.storeId, record.id, undefined, record); return record; }); }
    async getRecord(projectId: string, storeId: string, recordId: string, includeArchived = false) { const data = await this.store.snapshot(); this.requireStore(data, projectId, storeId, includeArchived); return this.requireRecord(data, projectId, storeId, recordId, includeArchived); }
    async updateRecord(input: { projectId: string; storeId: string; recordId: string; data: RecordData; replace?: boolean } & Client) { return this.store.transaction((state) => { const store = this.requireStore(state, input.projectId, input.storeId); const record = this.requireRecord(state, input.projectId, input.storeId, input.recordId); const before = structuredClone(record); record.data = this.validateRecord(store.schema.fields, input.replace ? input.data : { ...record.data, ...input.data }); record.updatedAt = now(); this.audit(state, "record.updated", input.client, input.projectId, input.storeId, record.id, before, record); return record; }); }
    async archiveRecord(projectId: string, storeId: string, recordId: string, client?: string) { return this.store.transaction((data) => { this.requireStore(data, projectId, storeId); const record = this.requireRecord(data, projectId, storeId, recordId); const before = structuredClone(record); record.archivedAt = now(); record.updatedAt = record.archivedAt; this.audit(data, "record.archived", client, projectId, storeId, recordId, before, record); return record; }); }
    async bulkRecords(input: { projectId: string; storeId: string; operations: ({ action: "create"; data: RecordData } | { action: "update"; recordId: string; data: RecordData; replace?: boolean } | { action: "archive"; recordId: string })[] } & Client) {
        if (!input.operations.length) throw new AtlasError("Bulk operations must contain at least one operation.");
        if (input.operations.length > 100) throw new AtlasError("Bulk operations are limited to 100 items.");
        return this.store.transaction((state) => { const store = this.requireStore(state, input.projectId, input.storeId); const results: AtlasRecord[] = []; for (const operation of input.operations) { if (operation.action === "create") { const stamp = now(); const record: AtlasRecord = { id: randomUUID(), projectId: input.projectId, storeId: input.storeId, data: this.validateRecord(store.schema.fields, operation.data), createdAt: stamp, updatedAt: stamp }; state.records.push(record); this.audit(state, "record.created", input.client, input.projectId, input.storeId, record.id, undefined, record); results.push(record); } else { const record = this.requireRecord(state, input.projectId, input.storeId, operation.recordId); const before = structuredClone(record); if (operation.action === "update") { record.data = this.validateRecord(store.schema.fields, operation.replace ? operation.data : { ...record.data, ...operation.data }); record.updatedAt = now(); this.audit(state, "record.updated", input.client, input.projectId, input.storeId, record.id, before, record); } else { record.archivedAt = now(); record.updatedAt = record.archivedAt; this.audit(state, "record.archived", input.client, input.projectId, input.storeId, record.id, before, record); } results.push(record); } } return { results }; });
    }
    async queryRecords(input: { projectId: string; storeId: string; filters?: RecordFilter[]; sort?: SortSpec[]; limit?: number; offset?: number; includeArchived?: boolean }): Promise<Page<AtlasRecord>> {
        const data = await this.store.snapshot(); const store = this.requireStore(data, input.projectId, input.storeId, input.includeArchived); const known = new Set(store.schema.fields.map((x) => x.name)); for (const filter of input.filters ?? []) { if (!known.has(filter.field)) throw new AtlasError(`Unknown filter field '${filter.field}' for store '${store.name}'.`); if(filter.operator==="in"&&!Array.isArray(filter.value)) throw new AtlasError(`Filter 'in' for '${filter.field}' requires an array value.`); } for (const sort of input.sort ?? []) if (!known.has(sort.field) && !["createdAt", "updatedAt"].includes(sort.field)) throw new AtlasError(`Unknown sort field '${sort.field}' for store '${store.name}'.`);
        return this.store.queryRecords(store,input);
    }
    async auditHistory(input: { projectId?: string; storeId?: string; recordId?: string; operation?: AuditOperation; limit?: number }) { const data = await this.store.snapshot(); const limit = Math.min(Math.max(input.limit ?? 50, 1), 200); return data.auditEvents.filter((x) => (!input.projectId || x.projectId === input.projectId) && (!input.storeId || x.storeId === input.storeId) && (!input.recordId || x.recordId === input.recordId) && (!input.operation || x.operation === input.operation)).sort((a, b) => b.occurredAt.localeCompare(a.occurredAt)).slice(0, limit); }

    private requireProject(data: AtlasData, id: string, archived = false) { const item = data.projects.find((x) => x.id === id && (archived || !x.archivedAt)); if (!item) throw new AtlasError(`Project '${id}' was not found${archived ? "" : " or is archived"}.`, "NOT_FOUND"); return item; }
    private requireStore(data: AtlasData, projectId: string, id: string, archived = false) { const item = data.stores.find((x) => x.id === id && x.projectId === projectId && (archived || !x.archivedAt)); if (!item) throw new AtlasError(`Store '${id}' was not found in project '${projectId}'${archived ? "" : " or is archived"}.`, "NOT_FOUND"); return item; }
    private requireRecord(data: AtlasData, projectId: string, storeId: string, id: string, archived = false) { const item = data.records.find((x) => x.id === id && x.projectId === projectId && x.storeId === storeId && (archived || !x.archivedAt)); if (!item) throw new AtlasError(`Record '${id}' was not found in store '${storeId}'${archived ? "" : " or is archived"}.`, "NOT_FOUND"); return item; }
    private unique(items: { id: string; name: string; archivedAt?: string }[], name: string, kind: string, except?: string) { if (items.some((x) => !x.archivedAt && x.id !== except && x.name.toLocaleLowerCase() === name.toLocaleLowerCase())) throw new AtlasError(`An active ${kind} named '${name}' already exists.`); }
    private audit(data: AtlasData, operation: AuditOperation, client: string | undefined, projectId: string, storeId?: string, recordId?: string, previous?: unknown, resulting?: unknown) { const event: AuditEvent = { id: randomUUID(), occurredAt: now(), client: client?.trim() || "unknown-client", operation, projectId, ...(storeId && { storeId }), ...(recordId && { recordId }), ...(previous !== undefined && { previous: structuredClone(previous) }), ...(resulting !== undefined && { resulting: structuredClone(resulting) }) }; data.auditEvents.push(event); }
    private validateSchema(fields: FieldDefinition[]) { if (!Array.isArray(fields) || fields.length === 0) throw new AtlasError("A store schema must contain at least one field."); const seen = new Set<string>(); return fields.map((raw) => { const field = structuredClone(raw); if (!/^[A-Za-z][A-Za-z0-9_]*$/.test(field.name)) throw new AtlasError(`Invalid field name '${field.name}'. Use letters, numbers, and underscores, starting with a letter.`); if (seen.has(field.name)) throw new AtlasError(`Duplicate schema field '${field.name}'.`); seen.add(field.name); if (field.type === "enum" && (!field.enumValues?.length || new Set(field.enumValues).size !== field.enumValues.length)) throw new AtlasError(`Enum field '${field.name}' requires unique enumValues.`); if (field.type !== "enum" && field.enumValues) throw new AtlasError(`enumValues is only valid for enum fields ('${field.name}').`); if (field.default !== undefined) this.assertType(field, field.default); return field; }); }
    private validateRecord(fields: FieldDefinition[], input: RecordData) { if (!input || typeof input !== "object" || Array.isArray(input)) throw new AtlasError("Record data must be an object."); const known = new Map(fields.map((x) => [x.name, x])); for (const key of Object.keys(input)) if (!known.has(key)) throw new AtlasError(`Unknown record field '${key}'.`); const output: RecordData = structuredClone(input); for (const field of fields) { if (output[field.name] === undefined && field.default !== undefined) output[field.name] = structuredClone(field.default); if (output[field.name] === undefined) { if (field.required) throw new AtlasError(`Required field '${field.name}' is missing.`); continue; } this.assertType(field, output[field.name]); } return output; }
    private assertType(field: FieldDefinition, value: unknown) { let valid = false; switch (field.type) { case "string": valid = typeof value === "string"; break; case "number": valid = typeof value === "number" && Number.isFinite(value); break; case "boolean": valid = typeof value === "boolean"; break; case "date": valid = typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`)); break; case "datetime": valid = typeof value === "string" && !Number.isNaN(Date.parse(value)); break; case "enum": valid = typeof value === "string" && !!field.enumValues?.includes(value); break; case "array": valid = Array.isArray(value); break; case "object": valid = !!value && typeof value === "object" && !Array.isArray(value); } if (!valid) throw new AtlasError(`Field '${field.name}' must be a valid ${field.type}${field.type === "enum" ? ` (${field.enumValues?.join(", ")})` : ""}.`); }
    private matches(actual: unknown, filter: RecordFilter) { switch (filter.operator) { case "eq": return Object.is(actual, filter.value); case "neq": return !Object.is(actual, filter.value); case "gt": return this.compare(actual, filter.value) > 0; case "gte": return this.compare(actual, filter.value) >= 0; case "lt": return this.compare(actual, filter.value) < 0; case "lte": return this.compare(actual, filter.value) <= 0; case "in": if (!Array.isArray(filter.value)) throw new AtlasError(`Filter 'in' for '${filter.field}' requires an array value.`); return filter.value.some((x) => Object.is(actual, x)); case "contains": return typeof actual === "string" ? actual.includes(String(filter.value)) : Array.isArray(actual) ? actual.some((x) => Object.is(x, filter.value)) : false; } }
    private compare(a: unknown, b: unknown) { if (a === b) return 0; if (a === undefined || a === null) return -1; if (b === undefined || b === null) return 1; return a < b ? -1 : 1; }
}
